# Generated by Django 4.2.9 on 2024-01-17 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_number', models.CharField(max_length=20)),
                ('vin', models.CharField(max_length=17, unique=True)),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TruckInUse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pick_up', models.DateField(blank=True, null=True)),
                ('drop', models.DateField(blank=True, null=True)),
                ('start_milage', models.IntegerField(blank=True, null=True)),
                ('end_milage', models.IntegerField(blank=True, null=True)),
                ('fuel_level', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TruckMake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TruckModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TruckStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
    ]
