# Generated by Django 4.2.9 on 2024-01-09 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hiring', '0002_driver_company_driver_middle_name'),
        ('fleet', '0002_truck_carrier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='truck',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hiring.driver'),
        ),
    ]
