# Generated by Django 4.2.9 on 2024-01-13 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0004_alter_truck_driver'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='truck',
            name='driver',
        ),
    ]
