# Generated by Django 5.0.1 on 2024-01-14 02:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0005_remove_truck_driver'),
        ('hiring', '0003_driver_truck'),
    ]

    operations = [
        migrations.CreateModel(
            name='TruckStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TruckInUse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pick_up', models.DateField(blank=True, null=True)),
                ('drop', models.DateField(blank=True, null=True)),
                ('start_milage', models.IntegerField(blank=True, null=True)),
                ('end_milage', models.IntegerField(blank=True, null=True)),
                ('fuel_level', models.IntegerField(blank=True, null=True)),
                ('drivers', models.ManyToManyField(to='hiring.driver')),
                ('truck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fleet.truck')),
            ],
        ),
    ]
