# Generated by Django 4.2.9 on 2024-01-17 12:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('maintenance', '0001_initial'),
        ('fleet', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='case',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maintenance.status'),
        ),
        migrations.AddField(
            model_name='case',
            name='truck',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fleet.truck'),
        ),
    ]
