# Generated by Django 4.2.9 on 2024-01-15 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0002_case_case_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='expense',
            field=models.CharField(default='TBD', max_length=500),
        ),
    ]
