# Generated by Django 4.2.9 on 2024-01-18 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0002_initial'),
        ('maintenance', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('days_interval', models.IntegerField(blank=True, null=True)),
                ('mile_interval', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TruckService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_service_date', models.DateField(blank=True, null=True)),
                ('last_service_milage', models.FloatField(blank=True, null=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trucks', to='maintenance.service')),
                ('truck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='fleet.truck')),
            ],
        ),
    ]
