# Generated by Django 4.2.9 on 2024-01-18 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0003_service_truckservice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='days_interval',
        ),
        migrations.RemoveField(
            model_name='service',
            name='mile_interval',
        ),
        migrations.AddField(
            model_name='truckservice',
            name='days_interval',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='truckservice',
            name='mile_interval',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
